pax

diff --git a/pax/packstrap b/pax/packstrap
--- a/pax/packstrap
+++ b/pax/packstrap
@@ -36,6 +36,41 @@ echo 'export GOPATH=$HOME/.go
 export PATH=${GOPATH//://bin:}/bin:$PATH' \
 >> .bashrc
 
+apt-get update
+apt-get install -y \
+    apt-transport-https \
+    ca-certificates \
+    curl \
+    keepalived \
+    open-iscsi \
+    ntp \
+    software-properties-common
+curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -
+add-apt-repository \
+   "deb https://download.docker.com/linux/$(. /etc/os-release; echo "$ID") \
+   $(lsb_release -cs) \
+   stable"
+curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key add -
+cat <<EOF >/etc/apt/sources.list.d/kubernetes.list
+deb http://apt.kubernetes.io/ kubernetes-xenial main
+EOF
+
+apt-get update
+apt-get install -yqq docker-ce=$(apt-cache madison docker-ce | grep 17.03 | head -1 | awk '{print $3}')
+
+# test snap
+  if ! test_cmd_loc="$(type -p "snap")" || [ -z "$test_cmd_loc" ]; then
+    echo "snap was not found in your path! skipping"
+  else
+    snap install --classic go
+    go get github.com/kubernetes-incubator/cri-tools/cmd/crictl
+  fi
+
+service open-iscsi restart
+apt-mark hold docker-ce
+
+swapoff --all
+
 if [ "$KUBEADM_INSTALL" = "openshift" ]; then
   # leaving clean for now, let ansible initialize
   #yum install -y centos-release-openshift-origin origin-clients
@@ -49,8 +84,7 @@ elif [ "$KUBEADM_INSTALL" = "kubeadm2ha" ]; then
   cd kubeadm2ha/ansible
   ansible-playbook -i $TMP/inventory cluster-images.yaml
 elif [ "$KUBEADM_INSTALL" = "kubeadm" ]; then
-  curl https://raw.githubusercontent.com/joshuacox/roustabout/master/KubadmNstall|bash
-  swapoff --all
+  apt-get install -yqq kubelet kubeadm kubectl
   kubeadm init
   kubeadm reset
 else
